export const WIZARD_SCENE_LOGIN = 'WIZARD_SCENE_LOGIN';
export const MATCH_INFORMATION_SCENE = 'MATCH_INFORMATION_SCENE';
export const LIVE_MATCH_SCENE = 'LIVE_MATCH_SCENE';
export const LEAGUE_INFO_SCENE = 'LEAGUE_INFO_SCENE';

export const MATCH_UPCOMING_SCENE = 'MATCH_UPCOMING_SCENE';
export const TODAY_MATCH_SCENE = 'TODAY_MATCH_SCENE';
export const WEEK_MATCH_SCENE = 'WEEK_MATCH_SCENE';
export const MONTH_MATCH_SCENE = 'MONTH_MATCH_SCENE';
export const NEXT_MONTH_MATCH_SCENE = 'NEXT_MONTH_MATCH_SCENE';

export const BotName = 'botP88';

export const PAGE_SIZE = 10;
